on:
  push:
    branches:
    - master
  pull_request:
name: "Flatpak"
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-nightly
      options: --privileged
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
      with:
        bundle: de.haeckerfelix.Shortwave.Devel.flatpak
        manifest-path: build-aux/de.haeckerfelix.Shortwave.Devel.json
        cache-key: flatpak-builder-${{ github.sha }}
